name: Docker Image CI

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          contex: .
          file: ./Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: st3sch/raven-bot:latest

